version: "3"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    depends_on:
      - nginx
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]

  letsencrypt-nginx-proxy-companion:
    depends_on:
      - nginx
      - nginx-gen
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - ./volumes/proxy/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  api:
    restart: always
    image: api
    build: ./build/api
    container_name: api
    environment:
      - VIRTUAL_HOST=api.kinokabaret.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.kinokabaret.com
      - LETSENCRYPT_EMAIL=support@kinokabaret.com

  website:
    restart: always
    image: website
    build: ./build/website
    container_name: website
    volumes:
      - "./volumes/nginx-website/conf.d/:/etc/nginx/conf.d"
      - "./volumes/config/website/config.js:/usr/share/nginx/html/config.js"
    environment:
      - VIRTUAL_HOST=kinokabaret.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=kinokabaret.com
      - LETSENCRYPT_EMAIL=support@kinokabaret.com

volumes:
  nginx_conf:
  nginx_html:
  nginx_vhost: